### ISSUE TITLE
add ability for multi country trips

### ISSUE THREAD

**Issue by LucaWintergerst** [timroes/gma-calculator#1]
I frequently visit multiple countries within one trip. An example calculation might look like this:

Netherlands:
Day 1 -  31€
Day 2 - 46€
Day 3 -  46€
Germany:
Day 4 - 24€
Day 5 - 24€
Day 6 - 12€

The main issue is that Day 3 is counted as 24h but the current calculator would count it as 12h when doing the calculations separately.
The workaround right now is to add a fourth day to the first part of the trip and mark all meals as paid for.

I suggest adding a way to override the 12h travel day. Two calculations would still be required but they would be cleaner and easier to create.

**Comment by timroes** [comment]
Already implemented. And we agreed in Slack, that it works as expected.
